### PR TITLE
Delete Smolin.jpg

### PR DESCRIPTION
**Pull request by smolinyakov**
delete pic

### CODE REVIEW

**Comment by fdech** [comment]
Ты зачем хочешь себя удалить?

**Comment by smolinyakov** [comment]
хз

**Comment by fdech** [comment]
Ок♥

**Comment by smolinyakov** [comment]
♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥

**Pull request merged**
